openapi: 3.0.0
info:
  title: openweathermap
  version: '1.0'
  description: gets weather details
  contact:
    name: Siddharth
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
